const card = [
  {
    url: "/assets/anime_girl_5.jpg",
    date: "11th",
    month: "Nov",
    year: "2022",
    title: "We are HnCCians",
    breif: "fdskjs ds dsifds dsk jdskj dsjfdsj fjkdsfjksd ",
  },
  {
    url: "/assets/anime_girl_5.jpg",
    date: "11th",
    month: "Nov",
    year: "2022",
    title: "We are HnCCians",
    breif: "fdskjs ds dsifds dsk jdskj dsjfdsj fjkdsfjksd ",
  },
  {
    url: "/assets/anime_girl_5.jpg",
    date: "11th",
    month: "Nov",
    year: "2022",
    title: "We are HnCCians",
    breif: "fdskjs ds dsifds dsk jdskj dsjfdsj fjkdsfjksd ",
  },
  {
    url: "/assets/anime_girl_5.jpg",
    date: "11th",
    month: "Nov",
    year: "2022",
    title: "We are HnCCians",
    breif: "fdskjs ds dsifds dsk jdskj dsjfdsj fjkdsfjksd ",
  },
  {
    url: "/assets/anime_girl_5.jpg",
    date: "11th",
    month: "Nov",
    year: "2022",
    title: "We are HnCCians",
    breif: "fdskjs ds dsifds dsk jdskj dsjfdsj fjkdsfjksd ",
  },
  {
    url: "/assets/anime_girl_5.jpg",
    date: "11th",
    month: "Nov",
    year: "2022",
    title: "We are HnCCians",
    breif: "fdskjs ds dsifds dsk jdskj dsjfdsj fjkdsfjksd ",
  },
  {
    url: "/assets/anime_girl_5.jpg",
    date: "11th",
    month: "Nov",
    year: "2022",
    title: "We are HnCCians",
    breif: "fdskjs ds dsifds dsk jdskj dsjfdsj fjkdsfjksd ",
  },
  {
    url: "/assets/anime_girl_5.jpg",
    date: "11th",
    month: "Nov",
    year: "2022",
    title: "We are HnCCians",
    breif: "fdskjs ds dsifds dsk jdskj dsjfdsj fjkdsfjksd ",
  },
  {
    url: "/assets/anime_girl_5.jpg",
    date: "11th",
    month: "Nov",
    year: "2022",
    title: "We are HnCCians",
    breif: "fdskjs ds dsifds dsk jdskj dsjfdsj fjkdsfjksd ",
  },
  {
    url: "/assets/anime_girl_5.jpg",
    date: "11th",
    month: "Nov",
    year: "2022",
    title: "We are HnCCians",
    breif: "fdskjs ds dsifds dsk jdskj dsjfdsj fjkdsfjksd ",
  },
  {
    url: "/assets/anime_girl_5.jpg",
    date: "11th",
    month: "Nov",
    year: "2022",
    title: "We are HnCCians",
    breif: "fdskjs ds dsifds dsk jdskj dsjfdsj fjkdsfjksd ",
  },
  {
    url: "/assets/anime_girl_5.jpg",
    date: "11th",
    month: "Nov",
    year: "2022",
    title: "We are HnCCians",
    breif: "fdskjs ds dsifds dsk jdskj dsjfdsj fjkdsfjksd ",
  },
  
];

export default card;
